version: "3"
networks:
    default:
        driver: bridge
    cms:
        external: true
services:
    caddy:
        image: "abiosoft/caddy:latest"
        volumes:
          - ./certs:/root/certs # to sync mkcert certificates to Caddy
          - ./Caddyfile:/etc/Caddyfile  # to mount custom Caddyfile
        ports:
          - "443:2015"